### ISSUE TITLE
Update to commonmark 0.21

### ISSUE THREAD

**Issue by c2h5oh** [golang-commonmark/markdown#1]
- [ ] stop converting tabs into 4 spaces
- [ ] make sure space/whitespace spec clarification is just a clarification and current implementation isn't broken
- [ ] close open tags at the end of `block quote` and `item list`
- [ ] implement 7 types of `html` block
- [ ] limit ordered list markers to 9 digits
- [ ] make sure link fragments and query parameters work correctly
- [ ] add support for nested links and emphasis

**Comment by opennota** [comment]
Updated to 0.28
