### ISSUE TITLE
Move to GitLab

### ISSUE THREAD

**Issue by opennota** [golang-commonmark/markdown#5]
- [x] Export to GitLab (DONE: see [gitlab.com/golang-commonmark](https://gitlab.com/golang-commonmark))
- [x] Update import paths
- [x] Update README.md on GitHub
- [ ] ~~Delete this repository 01-Oct-2018~~

**Comment by christophberger** [comment]
>  * [ ] Delete this repository 01-Oct-2018

Rather than deleting the repo, please just mark it as inactive. This way people still can find the project even if they only remember having seen it on Github (or if they follow an old link to Github). The Readme then shows them the way.

**Comment by opennota** [comment]
Okay. :)
